Azure/acr-builder

pkg/commands/archive_test.go
Build was failing because megacheck disallow passing nil context to any mthods
**Fixes #**  *[Refer closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)*:
megacheck build failure
```release-note
```
=> Fix megacheck error

tests/testCommon/file_server.go
**Fixes #28** 
The fix pings the file server to test the connection after it's started.
@sajayantony @shhsu
=> wait for file_server ready to avoid timing issue

.travis.yml
Adds support for Travis CI.
**Fixes #40**
This will build the main binary, run all tests (including tests for race conditions), and a simple linter. We can add `megacheck` and some other tools once we've cleaned up all the existing warnings.
=> Adds simple Travis CI

.travis.yml
Updates Travis CI to simply call `docker build`.
**Fixes #42**
---
=> Update Travis CI to simply call docker build

.dockerignore
Adds a basic `dockerignore` file so that some unnecessary files can be filtered out by the daemon.
**Fixes #46**
---
=> Adds dockerignore

Dockerfile
Switch base docker image to docker:17.12.0-ce-git
**Fixes #50**  *[Refer closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)*:
The change switches to ```docker:17.12.0-ce-git``` as base image which hs preinstalled docker and git. It then installs docker-compose and pip (which is required to install docker-compose and dependencies).
Along with the change, I also change acr-builder to built against 386 because amd64 doesn't work in the new base image.
@Azure/azure-container-registry @shhsu
=> Update to the latest docker cli

pkg/driver/build_test.go
**Fixes #54 **  *[Refer closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)*:
The unit test tried to validate the build timestamp against now() but sometimes failed as the actual diff was often slightly larger than 1s. Extend the duration buffer to 1m.
```release-note
```
=> increase the duration buffer in build timestamp validation

pkg/commands/docker.go, pkg/commands/docker_test.go
**Fixes #58  **  *[Refer closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)*:
add error logging for getRepoDigest
@Azure/azure-container-registry @shhsu
=> add error logging for getRepoDigest

pkg/driver/build.go
Ensure that build driver checks the image name argument.
**Fixes #11 **  *[Refer closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)*:
=> Output proper error message for missing docker image argument

pkg/build.go, pkg/commands/docker.go, pkg/commands/docker_test.go
**Fixes #67  
| name                                 | registry                            | repository          |
|:-----------------------------------|:---------------------------------|:----------------------|
| docker:1.7                          | registry.hub.docker.com | docker               |
| microsoft/dotnet:2.0           | registry.hub.docker.com | microsoft/dotnet |
| registry.azurecr.io/repo      | registry.azurecr.io           | repo                   |
=> fix the registry name for image from docker hub

README.md, main.go, pkg/commands/command_obfuscate.go, pkg/commands/docker.go, pkg/commands/docker_compose.go, pkg/commands/docker_compose_test.go, pkg/commands/docker_test.go, pkg/constants/program_args.go, pkg/driver/build.go, pkg/driver/build_test.go
**Fixes #63 
--docker-secret-build-arg sk1=sv1 --docker-secret-build-arg sk2=sv2 --docker-build-arg k1=v1
--build-arg k1=v1 --build-arg sk1=************* --build-arg sk2=*************
=> support secret build arg

.gitignore, main.go
Build duration is currently being printed out using `%s` in `main.go` which causes formats like `3d5h6s...` for longer times. This makes it harder to process, so instead just always use milliseconds.
**Fixes #72**
=> Convert the build duration to milliseconds

main.go, pkg/driver/build.go, pkg/driver/build_test.go
This PR completely removes build duration from the builder's output. Instead, the caller should be measuring the total time of the build request since it needs to anyways. I.e., the caller has to measure any overhead incurred while invoking the builder as well as timeout situations.
=> Remove build duration from logs

pkg/build.go, pkg/commands/git.go, pkg/commands/git_test.go, tests/mocks/pkg/context.go
**Fixes #55**
Sample output:
```json
[
{
"image": {
"registry": "xyz.azurecr.io",
"repository": "abc",
"digest": "sha256:0f0321435d1b35a9c233b439447730c75fe4e78bcbb7369a34e0a44a92572cad"
},
"runtime-dependency": {
"registry": "registry.hub.docker.com",
"repository": "docker",
"tag": "17.12.0-ce-git",
"digest": "sha256:14d3f9d0781478fb34802a197666dd7be5df0ffce46be2bd1dc2f0d814cfdcc9"
},
"buildtime-dependency": [
{
"registry": "registry.hub.docker.com",
"repository": "golang",
"tag": "1.9.1-stretch",
"digest": "sha256:f070a46c4bbb1f8486a64d1529ffc24113a5605ccaf29855b5d1cf6ef03daae2"
}
],
"git": {
"git-head-revision": "86ee62732b0a5f396ef3f3984c1d8d28f287833c"
}
}
]
```
=> add git reversion to image dependency

pkg/commands/docker.go, pkg/commands/docker_test.go, pkg/driver/build.go, pkg/driver/build_test.go, pkg/grok/docker_file.go, pkg/grok/docker_file_test.go, tests/resources/docker-dotnet/Dockerfile, tests/testCommon/helpers.go
**Fixes #**
https://github.com/Azure/acr-builder/issues/83
dependency scanning now knows build args
```release-note
```
=> grok to understand ARG directive and build args

.travis.yml
No reason to test with Docker in `RUN`, it slows everything down significantly by using layers. Just run `make` instead.
=> Faster Travis builds - no testing with Docker

pkg/build.go
Always use `latest` as the tag in the dependency output **unless** the path is a digest.
**Example Dockerfile**:
```
FROM hello-world@sha256:f5233545e43561214ca4891fd1157e1c3c563316ed8e237750d59bde73361e77
FROM golang:latest as blah
FROM golang as build
FROM docker:17.12.0-ce-git
```
**Example command**:
```
acr-builder -push --docker-registry ehotinger.azurecr.io -t "eric" -t "tests" -t "things"
```
**Output**
```
[
{
"image": {
"registry": "ehotinger.azurecr.io",
"repository": "eric",
"tag": "latest",
"digest": "sha256:271ce7ba399c8483fe085dfdf05003fa5dae0a781f8fbf98e481e62558f1c111"
},
"runtime-dependency": {
"registry": "registry.hub.docker.com",
"repository": "docker",
"tag": "17.12.0-ce-git",
"digest": …
```
=> Always use latest as a tag in the dependency output unless digest

main.go, pkg/build.go
Optimization and correctness. De-duplicate any provided image names to avoid duplicate builds, pushes, and dependency generation. For example, before if you passed in `-t eric -t eric:latest`, we would build twice against `latest`. Same goes if you were to even do `-t foo -t foo -t foo`. It's just a list and not a dictionary, so it's extremely easy to abuse. Now it's a hash and all image names that aren't a digest or have a tag are flagged as `latest`.
**Fixes #108**
=> De-dup provided image names to avoid duplicate builds, pushes, and deps

pkg/commands/docker.go, pkg/constants/etc.go
Don't query digests if the base image is `scratch`.
**Fixes #99**
```
[
{
"image": {
"registry": "ehotinger.azurecr.io",
"repository": "eric",
"tag": "latest",
"digest": "sha256:d096e3a5ec1792e0c1ca84097694e9c08535797b643c404a7150c7a42232a523"
},
"runtime-dependency": {
"registry": "registry.hub.docker.com",
"repository": "scratch",
"tag": "latest",
"digest": ""
},
"buildtime-dependency": null
}
]
```
=> Don't query digests if the base image is scratch

pkg/build.go, pkg/commands/docker.go, tests/resources/dockerfile-dups/ReductionDockerfile
Adds some additional logic to #102 to fully support the fully qualified URI on Docker Hub images and de-duplicating some `FROM` statements.
**Command**:
```
acr-builder -push -docker-file tests/resources/dockerfile-dups/ReductionDockerfile -t "library/eric:foo" -docker-registry ehotinger.azurecr.io
```
**Example Dockerfile**:
```
FROM alpine
FROM library/alpine
FROM alpine:latest
FROM library/alpine:latest
FROM library/golang
FROM golang
FROM library/golang:latest
FROM golang:latest
FROM ubuntu:latest
FROM ubuntu
FROM library/ubuntu
FROM library/ubuntu:latest
```
**Output:**
```
[
{
"image": {
"registry": "ehotinger.azurecr.io",
"repository": "library/eric",
"tag": "foo",
"digest": "sha256:92c414f2cf966fd4c6d60bc71180737bf878eeca3654cad82991a1e02d885d37"
}, …
```
=> Add library to the fully qualified URI of Docker Hub images

pkg/commands/docker.go, pkg/commands/docker_test.go
Don't prefix the registry name to image names if the image name already has the registry name prefixed. 
I.e., 
```
acr-builder -push -docker-file tests/resources/dockerfile-dups/ReductionDockerfile -t "ericrepo/eric:foo" -docker-registry ehotinger.azurecr.io -t "ehotinger.azurecr.io/eric:foo" -t "ehotinger.azurecr.io/foo" -t "blah"
```
Should not prefix `ehotinger.azurecr.io` to `ehotinger.azurecr.io/eric` or `ehotinger.azurecr.io/foo`.
**Fixes #111**
=> Don't prefix registry names if image names already have them as prefixes

.travis.yml, Makefile, tests/testCommon/file_server.go
Fixes #122 by ignoring an unhandled error. Adds errcheck to the `Makefile` and Travis so that this error can't make it in past PRs.
=> Ignore unhandled error

README.md, main.go, pkg/constants/exports.go, pkg/constants/program_args.go, pkg/driver/build.go, pkg/driver/build_test.go
Removes the `build-number` export. This functionality is already supported by means of normal build args.
=> Remove build number

vendor/github.com/docker/docker/builder/remotecontext/git/gitutils.go
=> allow falling back to clone the entire git repo

Dockerfile.Windows, README.md, isolation_test.go, main.go, pkg/commands/docker.go, pkg/commands/docker_test.go, pkg/constants/program_args.go, pkg/driver/build.go, pkg/driver/build_test.go
This PR enables windows container builds using acr-builder. As per https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility , Older containers will run the same on newer hosts with hyper-v isolation. Hence added a flag to enable hyper-v isolation for the docker build. Added the corresponding Dockerfile to build acr-builder for windows host.
Note:
We are using a patched version for docker CLI to workaround the named pipe issue. Please refer to https://github.com/Microsoft/go-winio/pull/78 for more details.
=> Enable Windows container builds with acr-builder.

Dockerfile, Dockerfile.Windows
Add `X-Meta-Source-Client` http header in Docker CLI config. The header will be passed to the registry when pull/push and allow the registry to track the client source.
=> set X-Meta-Source-Client header to ACR-BUILDER

.github/CODEOWNERS
Adds global code owners, these people will automatically be added to all PRs. @mnltejaswini @sajayantony @northtyphoon
=> Add default code owners

.gitignore
Updates the gitignore to ignore `*.exe` and `.vscode` directories if debugging on Windows. Removes glide because we use `dep` instead.
=> Update gitignore - ignore exes

Windows.Dockerfile
- Update the Windows Dockerfile to run unit tests (templating is now working cross-platform as a result of #153).
- Rename the binary to `acb.exe` for consistency.
=> Update Windows Dockerfile to run unit tests

Makefile, Makefile.windows, baseimages/scanner/Makefile, baseimages/scanner/Makefile.windows
- Updates the Makefile for Windows, so that `acb.exe` is produced from `make build` via `BINARY_SUFFIX`.
- Loads different `Makefile.{GOOS}` by trying to read `${GOOS}` if Go is installed, with a fallback if Go isn't installed.
- Fixes a bug in `make help`, where the correct text wouldn't be displayed on Windows.
- Adds `make vendor` which runs `dep ensure` - and ran it to update packages again.
=> Update Makefile for Windows

builder/builder.go, builder/parse.go, builder/parse_test.go
- Allow `parseArgs` to take multiple matches for CLI parameters (in the case of `tag`, it can be `--tag` or `-t`).
- Add tests for `parseArgs`
=> Allow parseArgs to take multiple matches for CLI parameters

builder/build_options.go, builder/builder.go, builder/parse.go, builder/parse_test.go, cli/build.go, cli/exec.go, cli/render.go, cli/shared.go, templating/base_render_options.go, templating/engine.go, templating/values_test.go
- Adds initial templating support for `build`
- Fixes a bug in `build` where `--pull` wasn't being set
- Removes `{{.Build.Tag}}` for now since it conflicts with `--tag` on `build` (and I'm not sure of its use case still)
```bash
$ acb build https://github.com/Azure/acr-builder.git -f Dockerfile -t "acr-builder:{{.Build.ID}}" -t 'acr-builder:{{now | date "20060102"}}' --id demo
...
Successfully tagged acr-builder:demo
Successfully tagged acr-builder:20180709
```
**Fixes #139**
=> - Adds initial templating support for `build`

cli/shared.go, templating/base_render_options.go, templating/values_test.go
First classes `{{.Build.Date}}`, which defaults to `time.Now().UTC()` with `yyyyMMdd-HHmmssz` format.
**Fixes #161**
/cc @SteveLasker
=> First class .Build.Date

cli/build.go, cli/exec.go, templating/base_render_options.go
- Enables `--network` during `build`, so that you can use a pre-defined network or `host` during `RUN` commands.
- Enables `--label` for metadata on images.
- Refactors some templating logic so that we just return an error if the template renders as an empty string rather than handling it in two places.
=> Enable --network and --label in build

README.md, baseimages/docker-cli/docker.Dockerfile, baseimages/docker-cli/docker.Windows.Dockerfile, baseimages/scanner/README.md, baseimages/scanner/Windows.Dockerfile, builder/builder.go, builder/constants_linux.go, builder/constants_windows.go, builder/context.go, builder/login.go, builder/push.go, builder/setup_linux.go, builder/setup_windows.go, docs/templates.md
- Adds the remaining support for Windows volumes.
- Enables `~/.docker/config.json` sharing for Windows across containers.
- Forces `push` to run in a container.
- Updates the docker CLI image for Windows.
- Updates docs.
**Fixes #134**
=> Windows support for volumes

builder/builder.go, builder/constants.go, builder/context.go, graph/dag_test.go, graph/step.go, graph/testdata/rally.yaml, templating/testdata/caching/cache.yaml, templating/testdata/helloworld/context-build.yaml, templating/testdata/helloworld/git-build.yaml, templating/testdata/helloworld/manifest.yaml, templating/testdata/helloworld/tar-build.yaml
- Adds `rm` and `detach` flags for steps. Both default to false.
NB: I've added `rm: true` to most of the examples so that when executing locally they're cleaned up nicely, but I think it makes sense to keep the default as false since cleanup won't matter on ACR and the default behavior of keeping them around is more useful for realistic complex pipelines.
**Fixes #172**
=> Add rm and detach

Dockerfile.Windows
Setup Windows credential helper and fix the docker config.json file warnings.
Fixes #176
=> Fix the warnings about loading config and setting up credential helper.

baseimages/scanner/models/image_dependencies.go, builder/context.go, builder/context_test.go
- Only output results of dependency scanning if there was an error (so that we can aggregate them at the end of Build)
- Refactor dependency parsing slightly, add some helper methods and a unit test.
=> Add tests for image dependency parsing

.dockerignore, README.md, baseimages/scanner/cmd/download.go, baseimages/scanner/scan/context.go, baseimages/scanner/scan/dependencies.go, builder/builder.go, builder/builder_test.go, builder/context.go, builder/push.go, cmd/build.go, cmd/exec.go, graph/dag.go, graph/dag_test.go, graph/step.go, graph/step_test.go, pkg/taskmanager/taskmanager.go
- Aggregate all image dependencies across multiple `build` steps and flush this information once at the end of the entire pipeline. 
- Simplify DAG traversal by first-classing the root node; `Nodes` will consist of all other vertexes, making a `range` loop easier.
- Update dockerignore to add a few additional files
- When querying digest, use `buf` instead of `os.StdErr`, this is a bug.
- Remove unused mutex from `builder`
- Misc. small refactorings
- Add a test for `getRepoDigest`
- Update README
- Use `log` instead of `fmt` in several places to add timing information in critical sections.
- Ignore errors in several places which are unrecoverable
**Fixes #184**
=> Aggregate image dependencies across multiple build steps

builder/builder.go
Wrap error if step fails so that it's more clear which specific step failed.
=> Wrap error if step fails so that it's more clear which specific step failed.

.github/PULL_REQUEST_TEMPLATE.md, README.md, builder/context.go, cmd/exec.go, cmd/render.go, cmd/shared.go, docs/acb.md, docs/templates.md, graph/dag_test.go, graph/step.go, graph/testdata/rally.yaml, templating/base_render_options.go, templating/testdata/caching/cache.yaml, templating/testdata/helloworld/context-build.yaml, templating/testdata/helloworld/git-build.yaml, templating/testdata/helloworld/manifest.yaml, templating/testdata/helloworld/tar-build.yaml
- Rename `--steps` to `--task`
- Remove `Rm` from Step in favor of `Keep`, so that the default behavior is to remove the container upon execution.
**Fixes #206**
**Fixes #202**
=> Rename CLI steps to task

builder/builder.go, graph/dag_test.go, graph/step.go, graph/step_test.go, graph/task.go, graph/testdata/rally.yaml
- Adds back in the `args` field. `cmd` takes precedence over `args` if both are present. Double quotes are the only thing we support, there is no reason to use single quotes as a delimiter.
Examples:
```
steps:
- cmd: bash -c "echo FROM busybox\nCOPY /hello RUN cat /hello > third.txt"
- cmd: bash -c "echo hello-world > test.txt && ls && cat test.txt"
- args:
- 'bash'
- '-c'
- |
echo "FROM busybox
COPY /hello 
RUN cat /hello" > someDockerfile
```
**Fixes #198**
=> Best-effort csv-style parsing for cmd, add back in args

Dockerfile
update acb image to be based on docker 18.06
=> update acb image to be based on docker 18.06

builder/builder.go, builder/context.go, graph/dag_test.go, graph/step.go, graph/step_test.go, graph/testdata/rally.yaml
Invoke /bin/sh by default to use the shell's field splitting algorithm
**Example**
```
steps:
- cmd: |
bash -c 'echo "FROM golang:1.10-alpine AS gobuild-base
RUN apk add --no-cache \
git \
make
FROM gobuild-base AS base
WORKDIR /go/src/github.com/ehotinger/scratch
COPY . .
RUN make static && mv scratch /usr/bin/scratch
FROM scratch
COPY --from=base /usr/bin/scratch /usr/bin/scratch
ENTRYPOINT [ "scratch" ]
CMD [ ]" > test.Dockerfile && cat test.Dockerfile'
- cmd: 'bash ls'
- build: -f test.Dockerfile -t scratch .
- cmd: 'bash rm test.Dockerfile'
- cmd: 'bash ls'
```
=> Invoke /bin/sh by default to use the shell's field splitting algorithm

pkg/grok/docker_file.go
Backport the quote fix for dependency parsing for Windows.
See https://github.com/Azure/acr/issues/115 for more info.
=> Backport the quote fix for dependency parsing for Windows

builder/context.go, graph/dag_test.go, graph/step.go, graph/testdata/acb.yaml
Allows specifying `--network` during run.
This is not fully first-classing networks, merely supporting a few basic scenarios to start off with. See https://github.com/Azure/acr-builder/issues/143 for more details.
=> Allows specifying network during run

pkg/procmanager/procmanager.go
Include a newline when printing failures to kill a process.
=> Include newline when printing procmanager fails

Dockerfile, baseimages/docker-cli/Dockerfile, baseimages/docker-cli/Windows.Dockerfile
Reverts 8919e8adc37761bc254dc8fef3702471b39d40f4 - there is an issue where VSTS is unable to clone.
=> Revert to 18.03

README.md, cmd/shared.go, docs/templates.md
Rename `--task` to `-f` and `--encoded-task` to `--encoded-file`
**Fixes #**
Closes #273
=> Rename --task to -f and --encoded-task to --encoded-file

cmd/shared.go, templating/base_render_options.go, templating/values_test.go
- Allow GOOS and GOARCH to be accessible from Run templating.
=> Allow GOOS and GOARCH to be accessible from Run

builder/builder.go, builder/context.go, graph/dag_test.go, graph/step.go, graph/testdata/acb.yaml
- Add support for expose
- Remove check for `--dry-run`, always try to set up the default network and home volume during a dry run.
**Fixes #293**
A follow-up issue: https://github.com/Azure/acr-builder/issues/296
=> Add support for expose

builder/builder.go, graph/network.go, graph/network_test.go, graph/step.go, graph/task.go
- Explicitly declare the driver as `bridge` on Linux and `nat` on Windows.
- Add the `Driver` property to `Network`.
- Print out the network being used during step execution
- Print out the network's driver type during network creation.
- Add unit tests for network
**Fixes #296**
=> Print out the network being used during step execution

cmd/build.go, cmd/exec.go, cmd/exec_test.go, cmd/shared.go, docs/templates.md, templating/base_render_options.go, templating/values_test.go
- Add `acb.yaml` as the default task name if neither a task file nor an encoded file are provided.
- Rename `SharedContextDirectory` to `SharedVolume`
**Fixes #268**
**Fixes #291**
=> Add acb.yaml as the default task name

appveyor.yml, templating/load_test.go
1. change autocrlf setting to true on appveyor CI which is same as our windows dev box environment
2. update two failed tests to be CRLF aware
=> Fix unit tests on windows

cmd/shared.go, templating/base_render_options.go, templating/values_test.go
Now that tasks and acb are deployed on Windows, I think it makes sense to expose `.Run.Architecture` so that you can have tasks that work cross-platform and reference different arch. IE: `windows/amd64` vs. `amd64`
=> Expose .Run.Architecture

cmd/exec.go, graph/task.go
- Allow setting a Task's default working directory from CLI instead of via yaml.
**Fixes #261**
=> Allow setting a Task's default working directory from CLI

.travis.yml
Golint has been moved.
More info here -> https://github.com/golang/lint#installation and golang/lint#417
=> fix golint path

templating/base_render_options.go, templating/base_render_options_test.go, templating/values_test.go
- Add RegistryName as a base rendering option for templates
**Fixes #322**
=> Add RegistryName as a base rendering option for templates

builder/builder.go, pkg/procmanager/procmanager.go
- Add logs for when containers are being launched or fail to exit with a valid exit code.
**Fixes #334**
=> Add logs for when containers are being launched or fail

builder/builder.go
- Add a warning message to github contexts that don't contain .git
**Fixes #321**
=> Add a warning message to github contexts that don't contain .git

builder/builder.go, builder/builder_test.go, graph/dag_test.go, graph/step.go, graph/step_test.go, graph/testdata/acb.yaml, pkg/procmanager/procmanager.go
- Allow steps to have an explicit `pull` property.
- Fix a small logging bug where `...` was placed after a newline.
**Fixes #319**
=> Allow steps to have an explicit pull property

builder/builder.go, builder/context.go, cmd/build.go, cmd/exec.go, cmd/render.go, cmd/scan.go
- Use `log` instead of `fmt` everywhere to prevent interleaving.
- Update the regex for capturing the JSON dependencies to include the time.
- When outputting dependencies, add a newline before the JSON string so that it's still nicely formatted and readable, i.e. it'll look like this now with timestamps:
```
2018/12/04 18:40:32 The following dependencies were found:
2018/12/04 18:40:32 
- image:
registry: acrbuilddemo.azurecr-test.io
repository: build-ng
tag: latest
digest: sha256:4c7bc8bcf1e8cc7d8cf4b3d502631a55568cfc1111d2e47bce3c134e25859dd0
runtime-dependency:
registry: registry.hub.docker.com
repository: library/nginx
tag: 1.13.3-alpine
digest: sha256:24a27241f0450b465f9e9deb30628c524aa81a1aa6936daa41ef7c4345515272
buildtime-dependency:
- registry: …
```
=> Use log everywhere instead of fmt to prevent interleaving

builder/builder.go, graph/dag_test.go, graph/step.go, graph/step_test.go, graph/testdata/acb.yaml, pkg/procmanager/procmanager.go
- Allows containers to be repeated after their initial execution. If multiple errors are encountered during the repetition, the last error will be recorded. If the step is marked as `ignoreErrors`, the final error will be ignored and the step will be marked successful.
- Fixes a bug where if a container fails to execute it will have its `retryDelay` invoked. Now we only sleep before the final failure.
**Fixes #320**
=> Allows steps to be repeated

builder/builder.go, builder/context.go, graph/task.go, graph/task_test.go, scan/dependencies.go, scan/scanner.go
- Differentiate between local and remote context during scanning to match Docker's behavior.
- Minor refactoring
**Fixes https://github.com/Azure/acr/issues/160**
**Fixes https://github.com/Azure/acr-builder/issues/286**
=> Differentiate between local and remote context for scanning

templating/base_render_options.go, templating/base_render_options_test.go, templating/testdata/curie/values.yaml, templating/values_test.go
- Allow passing Run/Values as JSON to containers.
There is one downside to this approach: since YAML can contain keys other than strings and JSON cannot, the default encoder can crash for complex objects, such as the Marie Curie example I've modified in this PR. This is well-discussed in the various yaml libraries and there are workarounds by either changing the default encoder from `map[interface{}]interface{}` to `map[string]interface{}`, or creating a custom recursive decoder. Since the yaml library that we're using is working on v3 with a possible design fix, I've opted to simply say we won't support these complex objects as a part of `--set` or `Values` for now. If it becomes a requirement we can either fork the library or create a custom decoder. Note: this …
=> Allow passing Run/Values as JSON to containers

cmd/acb/build.go, cmd/acb/build_test.go, cmd/acb/exec.go, cmd/acb/validation.go, cmd/acb/validation_test.go, graph/credential.go
When `push` flag is specified, the validation checks for source registry, username and password flags to be provided. But, since the `username` and `password` fields are stripped off by runner, and instead added to the `credentials`, we need to update the validation.
ALSO deprecates username/password
**Fixes #**
Update validation to check credential array instead of separate fields.
=> deprecate username/password

cmd/acb/commands/build/build.go, cmd/acb/commands/exec/exec.go
- CLI: rename credentials to credential for pluralization consistency.
**Fixes #383**
=> CLI: rename credentials to credential

.golangci.yml
- Use less cores for parallel tool runs; explicitly state linters used.
=> Use less cores for parallel tool runs; explicitly state linters used

vaults/azurekeyvault.go
Windows container handles 169.254.169.254 as local-link address and only route to on-link device by default. As the limitation, to allow acb talks to the msi token server on a different address, the change introduces a environment variable to override the default endpoint.
=> allow overriding the default msi endpoint

graph/network.go, graph/network_test.go, graph/task.go
- Make network name required. It'll error without a name and we just weren't doing any validation before.
=> Make network name required

graph/task.go, graph/task_test.go
Start validating/enforcing the version attribute on a Task.
There are currently two valid values:
- v1.0.0 (default)
- [1.0-preview-1](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-multi-step)
**Fixes #397**
=> Start validating version

graph/task.go, graph/task_test.go
- Print a warning instead of erroring if a version is invalid
See also: #418 for removing this warning message in the future.
=> Print a warning instead of erroring if a version is invalid

README.md, cmd/acb/commands/getsecret/getsecret.go, docs/templates.md
- Update template docs to indicate that `az acr build` doesn't support value-based templating but `az acr run` does.
=> Update template docs

cmd/acb/commands/download/download.go, scan/context.go, scan/git.go, scan/scanner.go
In the download.go, we fetch `CommitID` and `Branch` information of the Git context.
And we log it. 
Reason behind logging it is, it can be fetched by the STDOUT buffers for the client to fetch Git commit,branch information.
**Fixes #**
=> log commitID and branch information

cmd/acb/commands/build/build.go, cmd/acb/commands/build/build_test.go, graph/task.go, graph/task_test.go, scan/context.go
Allows passing in `working-directory` flag to build. This is to support building local context.
=> add support for working-directory for local build context

.travis.yml, Makefile, scripts/setup/dev_setup
- Update linter to 1.16
- Looks like Go 1.12.2 has broken us, so I'm hardcoding it to 1.12.1 for now.
- Prevents echoing the golang-ci command
=> Update linter to 1.16

builder/builder.go
Since the builder usually doesn't perform the download piece anymore, I've just removed that line (otherwise it appears multiple times which is slightly confusing), and instead we just say that we're scanning dependencies as a blanket statement.
=> Update scanning dependencies log messages

builder/context.go, builder/context_test.go, builder/parse.go, builder/parse_test.go, scan/dependencies.go, scan/dependencies_test.go
In the case of `docker build src/foo`, the Dockerfile will be looked at `src/foo`. Right now since we always default the Dockerfile to `Dockerfile`, we check at `.` when scanning for dependencies. This change makes it so that if we default the Dockerfile, we'll check for it relative to the specified context / working directory.
You can view an example of the current issue as this yaml: https://github.com/ehotinger/scratch/blob/master/acb-nested.yaml -- without this change the dependencies will be chosen from the Dockerfile in the root of the repository; with the change the dependencies are looked at in the proper subfolder.
**Fixes #434**
=> Update scanner to allow default Dockerfile path

cmd/acb/commands/getsecret/getsecret.go, docs/custom_registry_login.md, docs/getsecret_akv.md, docs/task-with-secrets.md, docs/task.md, graph/task.go, graph/task_test.go, graph/testdata/sequential.yaml, secretmgmt/secret.go, secretmgmt/secret_test.go, secretmgmt/secrets.go, secretmgmt/secrets_test.go, templating/base_render_options_test.go
- Refactor the `akv` yaml property to `keyvault`, this also renames many of the `Akv*` structs to be `KeyVault` instead.
=> Refactor akv to keyvault

graph/registry_credential.go
- Fixes a minor typo on the class name for registry credential
=> Fixes a minor typo on the class name for registry credential

builder/context_test.go, graph/task.go, graph/task_test.go, graph/testdata/acb.yaml
- When default environment variables were introduced with MSI, these environment variables were overriding the entire Task's environment variables. I.e., if you had `env: [foo=bar]` at the Task level with no defaults, you'll end up with an empty slice. Now, we merge them together.
This also refactors some of the tests and functionality in that area as I was poking around.
=> Fix Task level environment variables

builder/builder.go, cmd/acb/main.go, cmd/acb/main_test.go, pkg/procmanager/procmanager.go
The change add timeout information to the step logs.
2019/05/17 22:01:20 Executing step ID: acb_step_0. **Timeout(sec): 10**, Working directory: '', Network: 'acb_default_network'
2019/05/17 22:01:20 Launching container with name: acb_step_0
2019/05/17 22:01:30 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: **timed out**
**Fixes #382**
=> replace deadline exceeded message with timed out

.travis.yml, Dockerfile, Windows.Dockerfile
=> Bump Go version to 1.12.5

.dockerignore
- Update dockerignore to include yaml and Dockerfiles. Otherwise when you run `az acr run ...` the dockerignore will kick in causing you not to be able to use the `acb.yaml` or the Dockerfiles.
=> Update dockerignore to include yaml and Dockerfiles

builder/builder.go, builder/context.go, builder/context_test.go, builder/parse.go, builder/parse_test.go, cmd/acb/commands/download/download.go, cmd/acb/commands/scan/scan.go, scan/dependencies.go, scan/dependencies_test.go, scan/scanner.go
Fixes #495 
if --target is specified in build step, depdendency scan will parse the base images to the target stage.
=> support --target in dependency scan

cmd/acb/commands/exec/exec.go, graph/step.go, graph/step_test.go, graph/task.go
Adds the functionality to load images into docker store built with using buildx (cache: enabled flag).
If build contains no tags, we just append a buildx `--load` flag.
If build contains at least one tag, but no domain - we grab the Registry login server and create a cache image you can use in future for your builds.
If build contains at least one tag, and has a login server (fully qualified image name), we use that domain for image cache.
Fixes #
=> load images from cache if using buildx

Windows.Dockerfile, baseimages/docker-cli/Windows.Dockerfile
The change switches to official docker cli windows build for window container images.
As https://github.com/golang/go/issues/35447, the change also downgrades golang for windows to 1.13.2
Fixes #542 
Fixes #451
=> use official docker cli windows binary

README.md, builder/parse.go, util/trim.go, util/trim_test.go
- Allow the build step parser to handle quotes around arguments.
Fixes #537
=> handle quotes for docker build step args

cmd/acb/commands/build/build.go, templating/base_render_options.go, templating/base_render_options_test.go, templating/testdata/caching/Dockerfile-test
- fixes an bug where `LoadAndRenderSteps` tries to render secrets from build parameters if they contain the string "secrets" (ie. the tag name), a functionality used for exec. This breaks during unmarshal as the build content is usually not valid yaml.
- refactor the load and render methods so that build does not try to resolve secrets. We will expand the load logic of exec in the future so we decided to separate the paths now.
Fixes #540
=> Refactor load and render in templating

builder/constants_linux.go
Use bash as the config image for linux. Its size is 20% of ubuntu.
=> use bash as the default config image

Dockerfile, Windows.Dockerfile, builder/builder.go, builder/context.go, builder/context_test.go, cmd/acb/commands/build/build.go, graph/step.go, pkg/procmanager/procmanager.go, pkg/procmanager/procmanager_test.go
The change enables an auto-retry on windows build error timeout error (0xc0370109). To support retry on errors (stdout or stderr), the change introduces a retryOnErrors property on steps. So it can be explicitly specified on step.
```
steps:
- cmd: myimage 
retryOnErrorrs: ["error1", "error2"]
retries: 3 
```
The change also increases the windows build memory from default 1G to 2G and limits windows `docker` command container to 1 cpu.
=> add retryonerror for windows build

cmd/acb/commands/build/build.go
- retry on windows build error doesn't help. remove the auto-retry.
=> remove  auto-retry on windows build error

scan/context.go
- Read 2048 magic bytes to accommodate PAX tarfiles
https://github.com/docker/cli/pull/1770/files
Fixes #
=> Read 2048 magic bytes to accommodate extended pax

cmd/acb/commands/build/build.go, graph/task.go, util/prefixes.go, util/prefixes_test.go
In `acb build` command, the code always tries to prefix image tag with `registry`. However if the customer wants to build and push the image to another registry, the code unexpectedly alter the tag.
The change collects all known registries form the command option and skip the prefix if the tag already contains the registry.
=> fix mis-prefix custom registry image tag in build

cmd/acb/commands/exec/exec.go, pkg/procmanager/procmanager.go, scripts/setup/dev_setup
- added linter tag so gosec ignores build rule G204 just for line of code causing build to fail
- upgraded golangci-lint to v1.20.1
- working on fixing errors produced by upgrading to v1.27.0
Fixes #533
=> fix build issue with linter upgrade

cmd/acb/commands/build/build.go
- extend default push timeout for build command to 1 hour, it's to handle the large image push
=> extend default push timeout to 1 hour

go.mod, go.sum, scan/git.go, scan/git_test.go
The default branch of a git repo is not always "master".
github.com/repo.git => we should always use default branch no matter master exists or not or master is default or not
github.com/repo.git#dev => we should respect the settings, if dev doesn't exist, the download code should return error.
- 
Fixes #
=> fix acr build for git links without master branch

builder/builder.go, builder/digest.go, builder/digest_docker.go, builder/digest_remote.go, graph/step.go, scan/dependencies.go
- buildkit cannot get the built image dependencies using `docker image inspect`
- So it the manifest digest from the remote registry when buildkit is used.
Fixes #522 and #574
=> [buildkit] fetch digest from remote

graph/preprocessor_test.go, graph/testdata/preprocessor/valid-alias.yaml
This minor PR switches the remote alias test to use a url created from the current repository to avoid having a dependency on a remote repository.
=> Minor alias test update

scan/git.go, scan/git_test.go
- git version (2.38.1) started to block file protocol by default, the change explicitly allows it in unit test
Fixes #624
=> fix: allow git file protocol in unit test

.github/CODEOWNERS, builder/builder_test.go, builder/digest.go, builder/digest_docker.go, builder/digest_remote.go, scan/dependencies_test.go
- If the original image reference has `registry.hub.docker.com` prefix, we need to search the image by the reference name in the format of `registry/repository`, eg `registry.hub.docker.com/library/node` 
Fixes #643
=> fix: get digest of dockerhub image prefixed with registry.hub.docker.com

cmd/acb/commands/download/download.go, scan/context.go
Observed some "unexpected EOF" when downloading the context, so add more logs for troubleshooting.
time="2023-10-05T16:49:50Z" level=debug msg="Output from downloading: unexpected EOF\n"
time="2023-10-05T16:49:50Z" level=warning msg="Failed to download source context. Error: exit status 1"
I think "unexpected EOF" is likely originated from _**archive.Untar()**_. This method will throw "unexpected EOF" if the content is invalid or corrupted. If so, these logs may not be very helpful. Any suggestions?
Fixes #
=> add troubleshooting logs in acb download

scan/context.go
**Fix a bug left in my last PR**
I forgot to revert `r` to `buf`, resulting in "failed to untar context: archive/tar: invalid tar header".
=> fix a bug in download stream

builder/digest_remote.go, builder/digest_remote_test.go
- the resolver now requires both pull and resolve capabilities
- the resolver now requires pass empty credentials for anonymous access
Fixes #669
=> fix: misconfigured remote digest resolver

scan/git.go
- The PR reference for AzureDevOps is `refs/pull/<PR_ID>/merge`.
Fixes #672
=> feat(download): support ado pr ref

scan/git.go
- Just found for ADO, the PR ref can simply be `pull/<PR-ID>/merge` (`refs/` can be omitted), so it's better to include this format.
- Also, for GitHub, the PR ref can be `refs/pull/<PR-ID>/head` or `pull/<PR-ID>/head`.
- Locally tested with `acb download` with launch.json git commands.
Fixes #673
=> feat(download): support more formats of pr ref

graph/global-defaults-linux.go
- Updated the default image tag version for ACR CLI from 0.9 to 0.10
Fixes #
- none
=> chore : updated the default image tag version for acr cli

graph/global-defaults-linux.go
- Updated the default image tag version for ACR CLI from 0.10 to 0.11
Fixes #
- none
=> chore : updated the default image tag version for acr cli from 0.10 to 0.11

graph/preprocessor.go, graph/preprocessor_test.go
…because terraform will always encode escape yaml property keys
- Today we do not allow `"version": v1.1.0` when finding the tasks.yaml version during preprocess. This change allows the preprocessor to find the version key if the version key has been escaped.
Fixes #685
=> fix: allow escaped version key

graph/preprocessor.go, graph/preprocessor_test.go
- Today find version only checks the first line for the version. This allows the whole file to be checked instead.
Fixes #
=> fix: find version checks entire file and not just first line

scripts/setup/dev_setup
- update golangci-lint to support golang 1.24
=> fix(lint): update golangci-lint to support golang 1.24

azure-pipelines.yml
This PR fixes the Azure Pipeline to add a wrapper script around the Go binary. This is required for CodeQL analysis to work with Go 1.21+ on Linux, since Go binaries are now statically linked and CodeQL can no longer intercept the Go compiler directly.
- Added a script step that creates a Go wrapper (go-wrapper-bin/go) and prepends it to the PATH before the build.
- The wrapper delegates to the real Go binary, allowing CodeQL to "see" the build.
- Combined setup and build into a single script step, as required for CodeQL to intercept the build.
- Ensured golangci-lint is installed to a user-writable directory ($(GOPATH)/bin) and included in the PATH.
Fixes #
Should fix below during Code QL run: 
- go   | database finalize failed   |Database failed to finalize or no …
=> build: fix Code QL run for go

azure-pipelines.yml
- Attempting to fix code ql run for Go
**Fixes #**
- Moved the Go wrapper script from a local directory to the recommended temporary agent directory to adhere to MS code ql guidance here - https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/troubleshooting/onboarding/language-compiled#go-121-and-higher-on-linux
- Dynamically detecting the Go binary location using which go instead of hardcoding the path
- Prepended the wrapper directory to the PATH using the agent temp directory, ensuring the wrapper is used for all go invocations during the build.
=> build: more changes to fix code ql run for go

builder/builder.go, builder/constants.go, graph/step.go
- [April 16, 2025—KB5059091 (OS Build 17763.7249) Out-of-band - Microsoft Support](https://support.microsoft.com/en-us/topic/april-16-2025-kb5059091-os-build-17763-7249-out-of-band-328ff8b5-7c6b-4f06-95cc-67fbd18b3ffb) introduced a bug where-in the first time a Windows Server 2019 Hyper-V container is run in Windows 2022, it has a chance of failing. This fix will silently run the container once before the user runs it, to prevent the issue
=> fix: pre-run windows server 2019 containers to prevent startup issues

Dockerfile, Windows.Dockerfile, azure-pipelines-windows.yml, azure-pipelines.yml, go.mod, graph/global-defaults-linux.go
- update golang to 1.24.5
- update system images
=> chore: update golang and system images
