- .github/ISSUE_TEMPLATE.md
This adds a simple Github issue template to help standardize issue reporting.
> Adds a simple Github issue template

- pkg/commands/docker.go
- pkg/driver/build.go
- tests/mocks/pkg/context.go
- tests/testCommon/helpers.go
1. move digest query task after push task
2. use docker inspect command to get image digest from RepoDigests
**Fixes #52 **  *[Refer closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)*:
```release-note
```
> fix image digest query

- tests/resources/docker-hello-world/Dockerfile
Adding a faster hello-world test for acr builder. 
**Fixes #**  *[Refer closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)*:
Testing improvements. 
```release-note
```
> Added hello-world docker for faster test

- main.go
- pkg/constants/etc.go
- pkg/constants/exit_codes.go
- pkg/constants/exports.go
- pkg/constants/program_args.go
Updates error codes to be 1 if the builder fails unexpectedly.
**Fixes #64**
---
> Update exit codes to be 1 for general all-purpose errors.

- pkg/commands/docker.go
- pkg/commands/docker_compose.go
- pkg/commands/docker_test.go
- pkg/commands/git.go
- pkg/context.go
- pkg/shell/runner.go
- tests/mocks/pkg/context.go
**Fixes #74   *[Refer closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)*:
```release-note
```
> Fixes #74 - Use --password-stdin for docker login

- main.go
- pkg/commands/docker.go
- pkg/commands/docker_test.go
- pkg/constants/program_args.go
- pkg/driver/build.go
- pkg/driver/build_test.go
**Fixes #79 **  
**Fixes #82 ** 
> add --pull and --no-cache option

- pkg/commands/docker.go
- pkg/driver/build_test.go
- tests/mocks/pkg/context.go
- tests/testCommon/helpers.go
> skip push if --docker-image is not set

- pkg/commands/archive.go
- pkg/commands/archive_test.go
- tests/testCommon/file_server.go
See #89 
**Fixes #**  fixes #89
```release-note
```
> Understand archive format

- main.go
Adds flags for displaying help & binary version info
> Adds flags for displaying help & binary version info

- pkg/commands/archive.go
> Update the archiving to just use the response stream

- .travis.yml
- Dockerfile
https://github.com/golang/lint/issues/397
Workaround build failure related to golint
> workaround golint missing issue

- pkg/commands/docker_source.go
> stop logging full tar source url unless error

- vsts_bootstrap/docker.sh
Signed-off-by: Eric Hotinger <erhoting@microsoft.com>
> Removes an old unused VSTS bootstrap script.

- .travis.yml
- Updates Travis to build the scanner
> Updates Travis to build the scanner

- Dockerfile.Windows
- README.md
Update the Docker CLI version to latest that has the fix for named pipes for Windows container
> Update Dockerfile to use the latest docker CLI version which has the named pipe fix for windows container

- baseimages/scanner/cli/scan.go
- Adds an optional `--cleanup` flag for the scanner, so that it'll delete the destination folder (for a git clone or tar download) after scanning for dependencies.
**Fixes #144**
> Add --cleanup for scanner

- docs/templates.md
- Update template docs
**Fixes: #141**
> Update template docs

- baseimages/scanner/cli/scan.go
- baseimages/scanner/scan/git.go
- baseimages/scanner/scan/scanner.go
- builder/builder.go
- builder/context.go
- builder/login.go
- builder/push.go
- builder/setup_linux.go
- builder/setup_windows.go
- cmd/build.go
- cmd/exec.go
- cmd/init.go
- cmd/render.go
- cmd/root.go
- cmd/shared.go
- cmd/validation.go
- cmd/validation_test.go
- cmd/version.go
- main.go
- taskmanager/taskmanager.go
- volume/volume.go
- Add registry validation to exec
- Refactor "p" to "pipeline"
- Refactor cli to cmd
- Refactor cmder to taskmanager
**Fixes #166**
> Add registry validation to exec

- baseimages/docker-cli/Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- baseimages/docker-cli/docker.Dockerfile
- baseimages/git/Dockerfile
- baseimages/git/git.Dockerfile
Renames the Dockerfiles for the base images for consistency. Makes it easier to type rather than having to put special prefixes on each subfolder.
> Rename base images for consistency

- cmd/build.go
> Adds --platform to build

- builder/builder.go
- cmd/build.go
- docs/acb.md
- graph/dag_test.go
- graph/step.go
- graph/testdata/rally.yaml
Adds step start delay.
**Fixes #181**
> Adds step start delay

- baseimages/scanner/util/url_test.go
- pkg/taskmanager/taskmanager.go
- Adds tests for context validation
> Adds tests for context validation

- builder/builder.go
- Adds flavor text when outputting image dependencies
- Fix an issue with step start/time end.
> Adds flavor text when outputting image dependencies

- baseimages/scanner/cmd/scan.go
- builder/builder.go
- builder/push.go
- builder/setup_linux.go
- cmd/build.go
- cmd/exec.go
- cmd/render.go
- templating/engine.go
- Use log instead of fmt in several places
- Add a few new log lines for timing info
> Use log instead of fmt in several places

- cmd/exec.go
- templating/values.go
- Fixes a few warnings from ineffective assignments; spellcheck.
> Fix a few warnings: ineff assign, spellcheck

- builder/builder.go
- builder/context.go
- graph/dag_test.go
- graph/step.go
- graph/testdata/rally.yaml
Add user and privileged to Step.
> Add user and privileged to Step

- acb.windows.yaml
- acb.yaml
- builder/builder.go
- cmd/build.go
- docs/acb.md
- graph/dag_test.go
- graph/pipeline.go
- graph/step.go
- graph/step_test.go
- graph/testdata/rally.yaml
- graph/testdata/sequential.yaml
- templating/testdata/caching/cache.yaml
- templating/testdata/helloworld/context-build.yaml
- templating/testdata/helloworld/git-build.yaml
- templating/testdata/helloworld/manifest.yaml
- templating/testdata/helloworld/tar-build.yaml
> Rename run to cmd in Step

- README.md
- baseimages/scanner/cmd/download.go
- baseimages/scanner/cmd/scan.go
- baseimages/scanner/scan/git.go
- baseimages/scanner/scan/scanner.go
- builder/builder.go
- builder/context.go
- builder/login.go
- builder/push.go
- builder/setup_linux.go
- builder/setup_windows.go
- cmd/build.go
- cmd/exec.go
- docs/acb.md
- docs/templates.md
- graph/dag.go
- graph/dag_test.go
- graph/step.go
- graph/task.go
- graph/task_test.go
- pkg/procmanager/procmanager.go
- pkg/volume/volume.go
Rename pipeline to task, rename `taskmanager` to `procmanager`.
> Rename pipeline to task, rename taskmanager to procmanager

- templating/base_render_options.go
- templating/base_render_options_test.go
Better parsing for `--set`, allow values to contain equal signs in them.
> Better parsing for --set

- baseimages/docker-cli/Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
> upgrade docker-cli to 18.06

- acb.windows.yaml
- acb.yaml
- builder/builder.go
- builder/parse.go
- builder/parse_test.go
- cmd/build.go
- docs/acb.md
- graph/dag_test.go
- graph/step.go
- graph/step_test.go
- graph/task.go
- graph/testdata/rally.yaml
- util/parse.go
- util/parse_test.go
First-classes `build` as a property of `Step`, see the changed yaml for usage references.
**Fixes #200**
> First-class build in Step

- builder/builder.go
Log execution time when running a Step.
> Log execution time when running a Step

- cmd/exec.go
- cmd/render.go
- cmd/shared.go
- templating/base_render_options.go
- templating/load.go
- templating/load_test.go
Support Base64 encoded values/template files.
**Fixes #204**
> Support base64 encoding values/template files and mixing them

- docs/acb.md
- graph/dag_test.go
- graph/task.go
- graph/testdata/rally.yaml
Add Version to Task so that it's reserved for the future.
**Fixes #220**
> Add Version to Task so that it's reserved for the future

- docs/acb.md
> Doc update

- cmd/build.go
- util/prefixes.go
- util/prefixes_test.go
- Prefix registry name to image name for build command
**Fixes #242**
> Prefix registry name to image name for build command

- builder/context.go
**ref #233**
@ehotinger, I figured out how to repro the issue. After i changed the destination to the absolute path like /workspace/acb_step_0, the issue was gone.  =()
> workaround the unpacking hang issue

- builder/context.go
- cmd/download.go
- cmd/scan.go
- scan/scanner.go
**Fixes #233 **
Sort out the root cause of #233. Refine the fix.
> ensure scanner use absolute path

- cmd/build.go
- cmd/build_test.go
- util/prefixes.go
- util/prefixes_test.go
- Add a simple test for the build CLI.
- Don't scan for tags twice.
**Fixes #243**
> Add a simple test for the build CLI.

- builder/builder.go
- docs/acb.md
- graph/dag_test.go
- graph/step.go
- graph/task.go
- graph/testdata/acb.yaml
- templating/testdata/helloworld/context-build.yaml
- Rename `workDir` to `workingDirectory`.
**Fixes #253**
> Rename workDir to workingDirectory

- builder/builder.go
- When printing steps, print them top to bottom as read from the yaml
**Fixes #251 **
> When printing steps, print them top to bottom as read from the yaml

- builder/setup_windows.go
make sure the generated config.json file is ascii encoding.
**Fixes #**
> use ASCII encoding in config.json

- builder/builder.go
- builder/context.go
- cmd/build.go
- cmd/exec.go
- cmd/shared.go
- docs/acb.md
- docs/templates.md
- graph/dag_test.go
- graph/network.go
- graph/step.go
- graph/task.go
- graph/testdata/acb.yaml
- graph/testdata/sequential.yaml
- scan/dependencies.go
- templating/base_render_options.go
- templating/engine_test.go
- templating/load.go
- templating/load_test.go
- templating/template.go
- templating/template_test.go
- templating/testdata/helloworld/git-build.yaml
- templating/testdata/helloworld/values.yaml
- templating/values.go
- templating/values_test.go
Minor patches for various issues. Each commit corresponds to a particular issue. For the easiest review, I suggest reviewing each commit separately as they're completely isolated.
**Fixes #265**
**Fixes #260**
**Fixes #259**
**Fixes #258**
**Fixes #254**
**Fixes #252**
**Fixes #241**
**Fixes #143**
> Minor patches

- baseimages/docker-cli/Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- Up the version of the docker CLI to 18.06
> Up the version of the docker CLI to 18.06

- builder/parse.go
- builder/parse_test.go
Adds case insensitive parsing for visual studio git context.
> Adds case insensitive parsing for visual studio git context

- builder/builder.go
- Log out the step's working directory during processing
**Fixes #288**
> Log out the step's working directory during processing

- builder/context.go
- templating/base_render_options.go
Remove Windows PowerShell parsing TODO.
**Fixes #219**
> Remove Windows PowerShell parsing TODO

- Windows.Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- Fix the ARG reference in powershell.
- Revert docker cli to the previous version to be compatible with server.
> Fix widnows build

- cmd/build.go
- cmd/download.go
- scan/context.go
- scan/scanner.go
- templating/config.go
- templating/config_test.go
- templating/engine_test.go
- templating/load_test.go
- templating/values.go
- templating/values_test.go
- Adds more unit tests and some refactoring for templating.
- Remove the OCI flag from `acb build`
- Refactor docker source type from the scanner.
> Unit tests and refactoring for templating

- builder/context_test.go
- graph/network_test.go
- pkg/image/dependencies.go
- pkg/image/dependencies_test.go
- pkg/util/errors_test.go
- pkg/volume/volume.go
- pkg/volume/volume_test.go
- Add tests for dependencies
- Minor refactoring
- Unit tests for `errors`
> Add tests for dependencies

- builder/builder.go
- graph/dag_test.go
- graph/step.go
- graph/step_test.go
- graph/task.go
- graph/testdata/acb.yaml
- pkg/procmanager/procmanager.go
- pkg/procmanager/procmanager_test.go
- Minor updates to some tests; fix some edge cases
Fixes #180
> Minor updates to some tests; fix some edge cases

- templating/template_test.go
- Adds tests for nil templates
> Adds tests for nil templates

- Windows.Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- builder/constants_windows.go
> update windows docker file to support rs5

- builder/builder.go
- cmd/exec.go
- graph/dag_test.go
- graph/network.go
- graph/network_test.go
- graph/task.go
- graph/task_test.go
- graph/testdata/acb.yaml
add '--env' and '--network' to allow passing environment variable and network to containers.
> expose network and environment variable

- Dockerfile
- Windows.Dockerfile
- baseimages/docker-cli/Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
> disable prompt asking for credential

- Dockerfile
- Windows.Dockerfile
- baseimages/docker-cli/Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- scan/git.go
> support git-lfs

- graph/task.go
- templating/load_test.go
> Fix lint warnings

- scan/git.go
> Properly handle pat in git url

- builder/context.go
- builder/context_test.go
> use default isolation to run build step in windows

- cmd/shared.go
A minor text clarification for the CLI.
> Minor text clarification for CLI

- graph/step.go
- graph/step_test.go
- graph/task_test.go
Throw an exception if a step is multi-type.
**Fixes #270**
> Throw an exception if a step is multi-type

- templating/values_test.go
- Adds a test for merging template maps
As a part of #314
> Adds a test for merging template maps

- templating/base_render_options_test.go
- templating/testdata/caching/cache.yaml
- Adds a test for loading and rendering steps
**Fixes #314**
> Adds a test for loading and rendering steps

- cmd/build_test.go
- A trivial change to update a comment so that it actually makes sense.
> Update a comment to make sense

- builder/parse.go
- builder/parse_test.go
- Adds support for parsing Azure devops context paths
**Fixes #353**
> Adds support for parsing Azure devops context paths

- Windows.Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
Update go package sha in windows dockerfiles
> update go package sha

- .gometalinter.json
- builder/builder.go
- builder/parse.go
- builder/push.go
- cmd/acb/build.go
- cmd/acb/exec.go
- cmd/acb/render.go
- cmd/acb/validation.go
- graph/step.go
- graph/task.go
- scan/dependencies.go
- templating/base_render_options.go
- templating/engine.go
- templating/values.go
- Adds deadcode to linter. Helps keep dead code out of the repository.
- Fixes CI errors: use `` for regexp to avoid double escapes; all errors should start as lowercase.
> Adds deadcode to linter

- graph/credential.go
- Errors should begin as lowercase
> Errors should begin as lowercase

- templating/load_test.go
- templating/testdata/thames/values.yaml
> Global Readiness Fixes

- cmd/acb/validation_test.go
- graph/credential.go
- Delete unused function, refactor validation tests.
> Delete unused function, refactor validation tests

- builder/context.go
- builder/context_test.go
- Place positional arguments last in calls to scan.
> Place positional arguments last in calls to scan

- Windows.Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
Reduce the windows image size by ~360M
> remove golang package from windows images

- cmd/acb/commands/getsecret/getsecret.go
- docs/getsecret_akv.md
- templating/base_render_options.go
- templating/secrets.go
- templating/secrets_test.go
- vaults/azurekeyvault.go
- vaults/azurekeyvault_test.go
Extract keyvault AAD resource from Vault URL.
**Fixes #**
Fixes #398 
Tested it:
```sh
samashah@testacbvm:~$ cat task-secrets.yaml 
version: 1.0-preview-1
secrets:
- id: mysecret
akv: https://myacbvault32.vault.azure.net/secrets/SampleSecret/e20cbf6577194b50b3ec013c81c724d3
steps:
- cmd: bash echo mysecret value is {{.Secrets.mysecret}}
samashah@testacbvm:~$ sudo docker run -v $(pwd):/workspace --workdir /workspace \
> -v /var/run/docker.sock:/var/run/docker.sock acb exec  \
> --homevol $(pwd) -f task-secrets.yaml
2019/03/06 02:14:38 Using /home/samashah as the home volume
2019/03/06 02:14:39 Creating Docker network: acb_default_network, driver: 'bridge'
2019/03/06 02:14:39 Successfully set up Docker network: acb_default_network
2019/03/06 02:14:39 Setting up Docker …
```
> extract keyvault AAD resource from vault url

- Windows.Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
Removes a SHA check which broke on golang upgrade
**Fixes #**
Removes SHA check as its not needed.
> remove sha check

- builder/builder.go
- Allow passing environment variables to build step.
**Fixes #405**
> Allow passing environment variables to build step

- .github/CODEOWNERS
- Adds @shahzzzam as a default code reviewer / owner.
> Adds shahzzzam as a default code reviewer

- scan/context.go
- scan/scanner.go
- Wrap error message when failing to download source code
**Fixes #404**
> Wrap error message when failing to download source code

- cmd/acb/commands/getsecret/getsecret.go
- Use a 30 second timeout for getsecret by default
/cc @mnltejaswini  + @shahzzzam
> Use a 30 second timeout for getsecret by default

- README.md
- docs/task.md
- docs/templates.md
- graph/task.go
- Add YAML docs for Task
**Fixes #396**
> Add YAML docs for Task

- docs/task.md
- graph/step.go
- graph/task.go
- graph/testdata/acb.yaml
Breaking change: rename `env` to `envs` to match pluralization on `Step` with `Task`.
> Breaking change: rename envs to env

- cmd/acb/commands/build/build.go
- cmd/acb/commands/exec/exec.go
- docs/task.md
- graph/task.go
- graph/task_test.go
- graph/testdata/acb.yaml
- graph/testdata/sequential.yaml
- Remove Task's totalTimeout
**Fixes #416**
> Remove Task's totalTimeout

- cmd/acb/commands/build/build_test.go
- graph/step.go
- secretmgmt/secret_test.go
- Adds some missing unit test coverage.
> Additional unit test coverage

- cmd/acb/commands/build/build.go
- cmd/acb/commands/exec/exec.go
- cmd/acb/commands/render/render.go
- docs/custom_registry_login.md
- docs/task-with-secrets.md
- graph/registry_credential.go
- graph/registry_credential_test.go
- graph/task.go
- secretmgmt/secret.go
- secretmgmt/secret_test.go
- secretmgmt/secrets.go
- secretmgmt/secrets_test.go
- templating/base_render_options.go
- tokenutil/token_util.go
- Adds more documentation for custom credentials.
- Rename `armResourceId` to `aadResourceId`.
- Remove `az-cloud-name`
**Fixes #**
- Fix a bug where it couldn't make POST request using `client.Do`. So using `client.Post` instead.
> add docs, make couple bugfixes

- tokenutil/token_util.go
> add useragent info

- .travis.yml
- Run `make test` for travis CI
> Run make test for travis CI

- builder/builder.go
- Add a missing newline to log statement.
> Add a missing newline to log statement

- docs/templates.md
- Add `.Run.Branch` and `.Run.Branch` support in template docs.
> Docs: Add Commit and Branch

- scan/git.go
> dont write to stderr on git errors

- Windows.Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- builder/constants_windows.go
Update windows base image to 1903
> update windows base image to 1903

- builder/context.go
- builder/context_test.go
Specify user environment variables after the defaults.
**Fixes #452**
> Specify user environment variables after the defaults

- scan/git.go
Revert previous commit.
**Fixes #**
#448
> pass stderr to procManager

- graph/task.go
- graph/task_test.go
- Return an error if the Task's version is invalid
**Fixes #418**
> Return an error if the Task's version is invalid

- scripts/setup/dev_setup
> update linter to 1.17.1

- cmd/acb/commands/build/build.go
- cmd/acb/commands/exec/exec.go
- cmd/acb/commands/render/render.go
- templating/base_render_options.go
- templating/values_test.go
Signed-off-by: Eric Hotinger <ehotinger@gmail.com>
- Adds support for .Run.OSVersion.
> Adds support for .Run.OSVersion.

- README.md
This PR adds the badge for the build pipeline from last commit
> Windows build badge added

- README.md
This PR adds a Go Report Badge that shows some results on various code checks like lint and spelling.
> Go Report Badge added

- docs/templates.md
Add missing {{.Run.TaskName}} support doc
- 
Fixes #
> add taskName render doc

- graph/preprocessor.go
- graph/preprocessor_test.go
> fix version parsing

- .dependabot/config.yml
> turn dependabot off for now. Revisit later

- graph/preprocessor_test.go
> fix test which would fail on windows platform

- Dockerfile
- Windows.Dockerfile
- go.mod
> Bump Go version to 1.13.1

- templating/base_render_options.go
- templating/base_render_options_test.go
> fix empty alias rendering

- builder/builder.go
- builder/context.go
- builder/context_test.go
- graph/dag_test.go
- graph/preprocessor.go
- graph/step.go
- graph/task.go
- templating/load_test.go
- templating/values_test.go
- util/constants.go
> avoid fetching digest for buildx

- scripts/setup/dev_setup
> fix tag to v1.17 for golangci-lint

- cmd/acb/commands/exec/exec.go
> fix error msg

- Dockerfile
- Windows.Dockerfile
- baseimages/docker-cli/Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- scan/git.go
> enable credential cache

- graph/global-defaults-linux.go
> update linux command images

- .github/CODEOWNERS
- Windows.Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- builder/constants_windows.go
Upgrade windows base image to 1909
> Upgrade windows base image to 1909

- README.md
- This gives the ability to debug the Task runtime locally on your Linux machine.
Fixes #
> update readme with debug instructions

- scan/dependencies.go
- scan/dependencies_test.go
- templating/parse_image_dependency_test.go
- util/trim.go
- util/trim_test.go
- Handle quotes in Dockerfile FROM
Fixes #529
> Handle quotes in Dockerfile FROM

- Dockerfile
- Windows.Dockerfile
- baseimages/docker-cli/Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- upgrade golang and docker to the latest
> upgrade golang and docker

- graph/global-defaults-linux.go
Update linux built-in command image
> Alias: update built-in command image

- Windows.Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- builder/constants_windows.go
- upgrade windows base from 1909 to 2004
> update windows base to 2004

- secretmgmt/secrets.go
- vaults/azurekeyvault.go
- Improve and remove wrapped error message when resolving secrets in tasks file
Fixes #557 #548
> Improve Secrets Error Messages

- builder/builder.go
- Fix issue where volume defined with more than one file in Linux containers would fail
> Fix for Multi File Volume

- graph/global-defaults-linux.go
> update acr-cli to 0.3

- graph/global-defaults-linux.go
> update acr-cli to 0.4

- .github/CODEOWNERS
- scan/git.go
Fix acr build for pull request commit references, e.g., https://github.com/northtyphoon/node-helloworld.git#pull/1/head
- 
Fixes #
> fix acr build for pull request commit references

- .github/CODEOWNERS
- scan/git.go
Fix acr build for pull request commit references
Fixes #577
> fix acr build for pull request commit references (#578)

- .golangci.yml
- builder/digest_remote.go
- go.mod
- go.sum
- graph/step.go
- scan/git.go
Security: update containerd to 1.4.8
> update containerd to 1.4.8

- Dockerfile
- Windows.Dockerfile
- baseimages/docker-cli/Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
update docker version to the latest
> update docker version to the latest

- graph/global-defaults-linux.go
Update default linux images base on https://github.com/Azure/acr-task-commands/pull/14
> update default linux image

- .github/CODEOWNERS
- azure-pipelines-windows.yml
- azure-pipelines.yml
- Update owner
- Update Azure pipeline owner
> Update owner list

- README.md
- azure-pipelines-windows.yml
- azure-pipelines.yml
- update azure pipeline
Fixes #576
> update azure pipeline settings

- Dockerfile
- Windows.Dockerfile
- azure-pipelines-windows.yml
- azure-pipelines.yml
> update gotool to 1.17.9

- graph/global-defaults-linux.go
> update system images

- builder/builder.go
- docs/task.md
- graph/step.go
- support retry when downloading images #587  @northtyphoon  PTAL
> support retry when downloading images

- Dockerfile
- Makefile
- Windows.Dockerfile
- azure-pipelines-windows.yml
- azure-pipelines.yml
- go.mod
- scripts/setup/dev_setup
- Upgrade gotools to 1.18.3 #604
> upgrade go version to 1.18.3

- tokenutil/token_util.go
- properly handle status code from ACR exchange api
Fixes #613
> check exchange api response and return the appropriate error

- Windows.Dockerfile
- baseimages/docker-cli/Windows.Dockerfile
- fix windows docker build. the downloaded moby cli unpack files has been flattened
> fix docker build

- Dockerfile
- Windows.Dockerfile
- azure-pipelines-windows.yml
- azure-pipelines.yml
> upgrade golang to 1.18.5

- Dockerfile
- Windows.Dockerfile
- azure-pipelines-windows.yml
- azure-pipelines.yml
- graph/global-defaults-linux.go
- update golang to1.18.5
- update default image alias
> security: update dependency

- Dockerfile
- Windows.Dockerfile
- azure-pipelines-windows.yml
- azure-pipelines.yml
- the change switches to latest 1.18 version
> update golang to 1.18

- graph/global-defaults-linux.go
> security: dependency update

- go.mod
- go.sum
- scan/context.go
- vendor/golang.org/x/sync/AUTHORS
- vendor/golang.org/x/sync/CONTRIBUTORS
- vendor/golang.org/x/sync/errgroup/errgroup.go
- vendor/modules.txt
- vendor/oras.land/oras-go/v2/README.md
- vendor/oras.land/oras-go/v2/content.go
- vendor/oras.land/oras-go/v2/content/descriptor.go
- vendor/oras.land/oras-go/v2/content/file/file.go
- vendor/oras.land/oras-go/v2/content/file/utils.go
- vendor/oras.land/oras-go/v2/copy.go
- vendor/oras.land/oras-go/v2/extendedcopy.go
- vendor/oras.land/oras-go/v2/internal/descriptor/descriptor.go
- vendor/oras.land/oras-go/v2/internal/graph/memory.go
- vendor/oras.land/oras-go/v2/internal/slices/slice.go
- vendor/oras.land/oras-go/v2/internal/syncutil/limitgroup.go
- vendor/oras.land/oras-go/v2/pack.go
- vendor/oras.land/oras-go/v2/registry/reference.go
- vendor/oras.land/oras-go/v2/registry/remote/auth/client.go
- vendor/oras.land/oras-go/v2/registry/remote/auth/scope.go
- vendor/oras.land/oras-go/v2/registry/remote/registry.go
- vendor/oras.land/oras-go/v2/registry/remote/repository.go
- vendor/oras.land/oras-go/v2/registry/remote/retry/client.go
- vendor/oras.land/oras-go/v2/registry/remote/retry/policy.go
- vendor/oras.land/oras-go/v2/registry/repository.go
- update oras-go to v2 GA version
> maint: update oras-go to v2

- graph/global-defaults-linux.go
> maint: update acr-cli to v0.7

- graph/global-defaults-linux.go
- update system images to [db498d7](https://github.com/Azure/acr-task-commands/commit/db498d7b865bcfdf5f52b11b8723d23a4aad9c83)
> maint: update system images to db498d7

- graph/global-defaults-linux.go
- update system images to [28ba8fd](https://github.com/Azure/acr-task-commands/commit/28ba8fd89d2361ce9fcb6c4eedf061d4e1f9f5e3)
> maint: update update system images to 28ba8fd

- graph/global-defaults-linux.go
- update system images to [b689300](https://github.com/Azure/acr-task-commands/commit/b689300c9cf457d00e0b2b18cf13bf40164c0bfd)
> chore: update system images to b689300

- graph/global-defaults-linux.go
> chore: update acr-cli to 0.8

- cmd/acb/commands/download/download.go
- scan/context.go
> add troubleshooting logs in acb download

- scan/context.go
> improve streaming

- cmd/acb/commands/download/download.go
- scan/context.go
> add logs to verify changes

- scan/context.go
> Debugging acb download

- graph/global-defaults-linux.go
> chore: update system image

- Windows.Dockerfile
- update golang version in windows.dockerfile
> fix: update golang version in windows.dockerfile

- graph/global-defaults-linux.go
- update system images to [ee2fd89](https://github.com/Azure/acr-task-commands/commit/ee2fd89a36c16d3b164419ee46cb7e6dbb1c9a5d)
> chore: update system images

- graph/global-defaults-linux.go
- Added image alias for the new cssc image
- Updated the version of all other alias to the latest published tag 
Fixes #
- none
> Add alias for cssc image

- graph/global-defaults-linux.go
- Updated default image versions to the latest one
Fixes #
> chore: Update system image versions

- graph/global-defaults-linux.go
- Updated default image versions to the latest one
Fixes #
- None
> chore: Update system image versions to the newest version

- graph/global-defaults-linux.go
- Updated default image versions to the latest one
Fixes #
- NA
> chore: Updated cssc and all other system image versions to latest

- Dockerfile
- Windows.Dockerfile
- azure-pipelines-windows.yml
- azure-pipelines.yml
- go.mod
> chore: update golang to 1.24.2

- Dockerfile
- Windows.Dockerfile
- azure-pipelines-windows.yml
- azure-pipelines.yml
- go.mod
> chore: update golang to 1.24.6
